config/routes.rb
Rails.application.routes.draw do
 root "chatroom#index"
 get 'login', to: "sessions#new"
 post 'login', to: "sessions#create"
 delete 'logout', to:"sessions#destroy"
 post 'message', to: "messages#create"

 mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    validates :body , presence: true
    belongs_to :user
    scope :latest_messages, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
	validates :username, presence: true , length: {minimum:3 , maximum:10},
						uniqueness: { case_sensitive: false }
	has_secure_password
	has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?
    def current_user 
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        unless  logged_in?
            flash[:error] = " must login first to do that"
            redirect_to login_path
        end
    end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
    before_action :require_user

    def index
        @message  = Message.new
        @messages = Message.latest_messages
    end    
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :require_user

	def create 
		message = current_user.messages.build(message_params)
		if message.save 
			ActionCable.server.broadcast "chatroom_channel", 
										mod_message: message_render(message)
		end
	end

	private

	def message_params
		params.require(:message).permit(:body)
	end

	def message_render(message)
		render partial: message, locals: {message: message}
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :login_restriction, only: [:create, :new]

    def new
        
    end

    def create
        user = User.find_by(username: params[:session][:username])
        if user and user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "successfully logged in"
            redirect_to root_path
        else
           flash.now[:error] = "wrong info" 
           render :new
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "successly logged out"
        redirect_to login_path
    end

    private

    def login_restriction
        if logged_in?
            flash[:error] = "you are already logged in "
            redirect_to root_path
        end
    end

    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chatroom/_sidemenu.html.erb
<div class="ui vertical yellow text menu">
  <div class="header item">Online Users</div>
  <a class="active item">
    Closest
  </a>
  <a class="item">
    Most Comments
  </a>
  <a class="item">
    Most Popular
  </a>
</div>

app/views/chatroom/index.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular blue users icon"></i>
  Message Sonic
</h2>
<div class = "ui two column grid">
    <div class = " twelve wide column">
        <div class= "ui fluid raised card chatbox">
            <div class= "content" id="messages">
                <div class="ui feed" id="message-container">
                    <%= render @messages %>
                </div>
            </div>
            <div class = "extra content">
                <%= form_for(@message, html:{class:"ui reply form", role: "form"}, url: message_path, remote: true) do |f|   %>
                    <div class="field">
                        <div class="ui fluid icon input">
                            <%= f.text_field :body%>
                            <%= f.button '<i class="icon edit"></i>'.html_safe %>
                <% end %>        
                        </div>
                    </div>
            </div>
        </div>
    </div>
    <div class = "four wide column">
        <div class= "ui fluid raised card chatbox">
            <div class= "content">
                <%= render "chatroom/sidemenu" %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_flash.html.erb
 <% flash.each do |message_type,message_content| %>
 	<div class="ui <%= message_type %> message transition">
  		<i class="close icon"></i>
 	 	<div class="header">
    		<%= message_content  %>
  		</div>
	</div>

 <% end %>

app/views/layouts/_menu.html.erb
<div class="ui huge blue menu">
  <div class="ui container">
    <%= link_to("Chatroom", root_path ,class: "active item") %>
    <a class="item">
        Messages
    </a>
    <div class="right menu">
      <div class="ui dropdown item">
        Account <i class="dropdown icon"></i>
        <div class="menu">
        <% if logged_in? %>
          <%= link_to "Logout", logout_path, method: :delete, class:"item" %>
        <% else %>
          <%= link_to "Login", login_path, class:"item" %>
          <%= link_to "Sign Up", root_path ,class:"item"%>
        <% end %>
        </div>
      </div>
      <% unless logged_in? %>
        <div class="item">
          <%= link_to "Sign Up", root_path, class:"ui primary button"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageSonic</title>
      <%= favicon_link_tag %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body backgroundcolor= "#FBFCFC">
    <%= render 'layouts/menu' %>
    <div class="ui container">
      <%= render 'layouts/flash'  %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
    <div class="event">
      <div class="content">
        <div class="summary">
            <em><%= message.user.username %></em>: <%= message.body %>
        </div>
      </div>
    </div>